### ISSUE TITLE
fails to work in 32bit or 64bit Visual studio 2015 14.0.25123.00 update 2

### ISSUE THREAD

**Issue by KoenigLear** [nunit/nunit-vs-adapter#112]
Hi,

 Nunit Adapter fails after an update:

**Previous NUnit version worked fine!! IMHO this change is breaking it:**
https://github.com/nunit/nunit/commit/70c35b12b8250c590ca351ec2623226dc3df16b9?_pjax=%23js-repo-pjax-container

**Running on 32 bits says:**
Cannot run tests in process - a 32 bit process is required.

**Running on 64 bits gets stuck:**
Cannot discover test extensions installed by NuGet. The NuGet service is not available. Tests may not be found due to missing test adapter extensions.
NUnit Adapter 3.2.0.0: Test discovery starting
NUnit Adapter 3.2.0.0: Test discovery complete
========== Discover test finished: 50 found (0:00:00.5001464) ==========
------ Run test started ------
Cannot discover test extensions installed by NuGet. The NuGet service is not available. Tests may not be found due to missing test adapter extensions.
NUnit Adapter 3.2.0.0: Test execution started
Running all tests in ...
NUnit3TestExecutor converted 50 of 50 NUnit test cases

**Comment by rprouse** [comment]
This is filed against the wrong project, but we can help you here.

I think you are correct in your assessment of the change that is causing the error. I think that code should first check if we are already running 32bit and not do that check if we are. @CharliePoole do you agree? If so, we should create a high priority issue in the Nunit Project to get it fixed. It may require an engine hotfix and an update to the adapter. Unfortunately we can't advise people to go back to the older version since Visual Studio auto-updates now.

@KoenigLear, you say 64 bit gets stuck. It looks like it is discovering tests, but not finishing? Is that correct?

**Comment by KoenigLear** [comment]
@rprouse  it finishes the discovery, is the executor that gets stuck, see the last line. Unfortunately it doesn't ouput any other message.  I need to restart VS to try anything else.

Note: as a work around i changed the reference of my project to 2.6.4, and ran my tests using the Nunit.exe interface 64bit, not ideal but works.   Look forward to an update from you guys. :)

**Comment by CharliePoole** [comment]
@KoenigLear It can't be the code you are suggesting, since that's in the console runner, which you are not using. It's actually coming from here:

https://github.com/nunit/nunit/blob/fe3ef10843dcef8f789f65d8b484cb975a3b1410/src/NUnitEngine/nunit.engine/Runners/MasterTestRunner.cs#L90

That code was added in case some other runner slipped an invalid setting combination into the engine. However, it incorrectly assumes that all package settings come from the user and that's not the case.

The ProcessModel setting is hard-coded into the adapter and is always "InProcess"
The RunAsX86 setting is not used by the adapter but the engine itself may set it if it decides that your tests need to be run as 32-bit. Apparently, that's what the engine has decided WRT your test. Is it a 32-bit assembly or is the engine's analysis incorrect?

Can you clarify how you are telling us to run as 32- versus 64-bit?

**Comment by CharliePoole** [comment]
@rprouse You're quite right, we should also check if the current process is 32 bit, but only if we are planning to run in the current process. Otherwise, it would make no sense.

**Comment by KoenigLear** [comment]
@CharliePoole  the message appears when I set Platform Target 32bit on an exe project.  I assume the Nunit adpater should be able to find the right Nunit execution engine.

As it turns out 64bit is working fine now! the fix seemed related to removing the nunit 3.1x dll and re-adding it. Something may have happened during the update...

**Comment by CharliePoole** [comment]
There's only one execution engine on this case, the one bundled with the adapter. Whether it finds itself in a 32- or 64-bit process is up to VS.

**Comment by CharliePoole** [comment]
Look for extra versions of the engine in the packages directory. Sometimes nuget leaves things around after an upgrade and nunit doesn't deal well with that.

**Comment by KoenigLear** [comment]
I had a look at the nunitframework.dll it says Architecture:Any 64 bit preferred.  Is there a specific 32 bit dll? would I need to load a different Nuget package?

**Comment by CharliePoole** [comment]
No, as explained it's an error in the code. The master test runner is assuming without checking that it's in a 64-bit process even though VS has loaded it into a 64-bit process.

**Comment by CharliePoole** [comment]
I'm closing this in favor of issue nunit/nunit3-vs-adapter#181
