### ISSUE TITLE
VS Text Explorer only shows 20 tests

### ISSUE THREAD

**Issue by pgrm** [nunit/nunit-vs-adapter#121]
Hi, 

I'm using .net core with this kind of project.json:

`````
{
  "version": "1.0.0-*",
  "testRunner": "nunit",

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Moq": "4.6.25-alpha",
    "dotnet-test-nunit": "3.4.0-beta-1",
    "System.Diagnostics.TraceSource": "4.0.0",
    "NUnit": "3.4.1"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  }
}
````

I have 4 Test projects and for one of them (the above project.json) I know for sure, that Visual Studio cannot find all the tests. Currently it finds 20 tests, but there should be 20 just in the new test project.

For instance, given these test cases:

    [TestCase(null, null, null, false)]
    [TestCase(null, null, "..", true)]
    [TestCase(null, "..", null, false)]
    [TestCase(null, "..", "..", false)]
    [TestCase(1234, null, null, false)]
    [TestCase(1234, null, "..", false)]
    [TestCase(1234, "..", null, false)]
    [TestCase(1234, "..", "..", false)]
    public void CodeNextValueConfigurationValidationTest(int? step, string customNextNumber, string customNextCode, bool isValid)
    {
        Assert.AreEqual(isValid, ...);
    }

It finds the test case 

    Test Name:	CodeNextValueConfigurationValidationTest(1234,"..","..",False)

but not the others.

Other TestCases are found as a whole and again other simple tests, just functions marked with `[Test]` cannot be found at all.

But if I run `dotnet test` in the command line, all tests are run. I tried reloading the project, restarting VS, ... but nothing helped. I have NUnit 3 Test Adapter Version 3.4.0 installed.

Any thoughts what else I can try? thx

**Update:**

I just disabled NUnit 2.0 and restarted VS and saw the 20 test from my current file. After rebuilding the solution again, I see the same as before. It seems to me that I always see a more or less random subset of 20 tests. That's weird, isn't it?

And when I try to run all tests, it also just runs those 20

The pattern seems to be, that for this file I'm analyzing it takes the last 9 tests / testcases

**Comment by CharliePoole** [comment]
FWIW, this repository is for the (old) NUnit Test Adapter, which supports NUnit 2.6.4 and is at version 2.0. We can discuss it here but if it looks like there is a bug in the NUnit 3 Test Adapter I'll move it over there.

At first glance, it doesn't seem to me that there is a bug here, since our adapter doesn't support .NET Core at this time. We plan for it to do so, but that will require substantial changes. @rprouse would you chime in with instructions for how to run .NET Core under the test window using the Microsoft tooling?

The possible issue I see for the NUnit 3 adapter is that it should be giving some sort of error message or warning. What are you seeing listed in the Output window on discovery?

**Comment by pgrm** [comment]
Thx for the note, I've moved it to https://github.com/nunit/nunit3-vs-adapter/issues/203 and I'll answer your question there

**Comment by rprouse** [comment]
@CharliePoole if you see `project.json` or .NET Core mentioned, it isn't the v3 adapter, but the `dotnet-test-nunit` repository it should be moved to. `dotnet-test-nunit` does all the integration with Visual Studio for .NET Core along with the command line running :wink:

**Comment by CharliePoole** [comment]
I figured that is what he should be using, but it sounded like he was saying he used the VS adapter. Maybe we need to think about what we call things, so users can distinguish.

Also, is there a potential issue for users who do try to use the VS Adapter for .NET Core? What happens if you add the adapter package to a .NET Core project? Is it sufficiently user-friendly?

@pgrm In our defense, we had the idea that separate issue data bases, one per repo, would make it easier for users, not harder!

@pgrm If you end up in the wrong repo, it's OK to just wait for us to decide to move it rather than doing copy/paste. We can now do that at a push of a button, copying all the discussion.

**Comment by rprouse** [comment]
> Maybe we need to think about what we call things, so users can distinguish.

Unfortunately, the .NET Core runner has to be named `dotnet-test-nunit`. The convention is hard coded into .NET Core I believe.

> Also, is there a potential issue for users who do try to use the VS Adapter for .NET Core? What happens if you add the adapter package to a .NET Core project? Is it sufficiently user-friendly?

I should try it. I do have the V3 adapter installed as a VSIX and it doesn't attempt to load or run the .NET Core tests.

**Comment by CharliePoole** [comment]
Hard coded naming! Why am I not surprised?
