### ISSUE TITLE
NUnit3 tests makes nunit-vs-adpater to fail TFS build

### ISSUE THREAD

**Issue by jepzen** [nunit/nunit-vs-adapter#138]
As Charlie mentioned in his answer http://stackoverflow.com/a/35193783/1016439 here the nunit-vs-adapter casues an exception when executed on TFS build. All tests get discovered and run but if another project contains NUnit 3 tests the whole build step get marked as failed even though all tests passes.

I attached a test run from a solution which contains both Nunit 2 and 3 in different projects. All test passes but still the overall result for the build step a fail

![test_fail](https://cloud.githubusercontent.com/assets/592127/22332209/005a8d12-e3d0-11e6-8871-033622151aec.PNG)

**Comment by LazyTarget** [comment]
We have this very issue, although only one test project in the solution and it only references NUnit 3 and the NUnit 3 Test Adapter. As the Stack Overflow answer suggests, that it is the NUnit 2 Test adapter that throws this error, but I can't see that it is being referenced anywhere.

* I've tried installing/disabling the .vsix extension on the build server.
* I've verified that the NUnit 2 adapter isn't referenced in the packages.config or that it exists in the /packages folder on the TFS server.

Works fine on the dev machine, but that might be because I have Resharper installed.

**Comment by CharliePoole** [comment]
@LazyTarget When you say it works on the dev machine, is that in the IDE or from the  command-line? This is a known problem only with vstest.exe - the IDE handles it fine.

Clearly, the NUnit2 adapter is __somewhere__ on your build machine. The messages starting "NUnit VS adapter 2.0.0.0..." are actually from the adapter. Is it possible that your build system is being restored from a saved image that includes the 2.0 adapter?

**Comment by ChrisMaddock** [comment]
There's an accepted bug which may be relevant here - relating to vstest invoking adapters for projects with no reference to the adapter.

**Comment by OsirisTerje** [comment]
Is this still the case?
