### ISSUE TITLE
Exception thrown discovering tests - could not load type

### ISSUE THREAD

**Issue by MarkoFilipcic** [nunit/nunit-vs-adapter#26]
Visual studio throws an exception while discovering tests.

NUnit 1.0.0.0 discovering tests is started
Exception thrown discovering tests in ****
System.TypeLoadException: Could not load type 'System.Record' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

Where mscorlib is 
Script# Core Assembly
ScriptSharp.0.7.5.1\tools\mscorlib.dll
version 0.7.0.0

**Comment by Maultasche** [comment]
This was happening to me. It turned out that there was some code in the default constructors of one of my classes that was throwing an exception when the NUnit test adapter was coming through and constructing classes while looking for tests.

The exceptions weren't occurring when the application was running because everything had been set up correctly. Nunit is probably constructing the class in isolation and the default constructor code fails due to incomplete setup. I was able to move the offending code out of the default constructor and the discovering tests error went away.
