### ISSUE TITLE
Test Adapter Possibly using the wrong version of Microsoft.VisualStudio.TestPlatform.ObjectModel

### ISSUE THREAD

**Issue by forestmarie** [nunit/nunit-vs-adapter#72]
I'm having an issue getting my build server to run my unit test suite. Here's the details:

We're using NUnit 2.6.4
The build server is running TFS Build 2012 with Update 4
The TFS server is running TFS 2013 with Update 2
I have my build controller set up to point to a version controlled folder that has 3rd party dependencies - in this folder are the 4 NUnit dependencies need to run NUnit tests on the build server.
The Test Runner is setup properly to use Visual Studio's test runner
Both Visual Studio 2012 and Visual Studio 2013 with Update 4 are installed on the build server
When I check-in via a gated checkin through my build definition, I get this error:

TF900546: An unexpected error occurred while running the RunTests activity: 'Could not load type 'Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestExecutorLauncher2' from assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.'.

This is the same problem found at:

VS2013, TFS 2012 AutomatedTest NUnit not working problems

I'm using NUnit's latest Test Adapter found at: https://visualstudiogallery.msdn.microsoft.com/6ab922d0-21c0-4f06-ab5f-4ecd1fe7175d

When I decompile this assembly I see that adapter has a dependency on Microsoft.VisualStudio.TestPlatform.ObjectModel version 11.00.

What is interesting here is looking through Client namespace of that class, there is no ITestExecutorLauncher2 which is what the run tests activity is looking for (I think). However, ITestExecutorLauncher2 is found in version 12.00 of Microsoft.VisualStudio.TestPlatform.ObjectModel.

My question is am do I have something misconfigured here or should NUnit.VisualStudio.TestAdapter, Version=2.0.0.0 reference version 12.00 of Microsoft.VisualStudio.TestPlatform.ObjectModel and not version 11.00?

**Comment by OsirisTerje** [comment]
The Microsoft test runners , vstest.discoveryengine and vstest.executionengine both search the test adapters for an ExtensionUri attribute with an executionUri, which in NUnits case is 
public const string ExecutorUri = "executor://NUnitTestExecutor";
Whatever class has that attribute will be used for discovery and execution. 

The reference to the VS2012 version is intentional.  Using that reference the adapter will run on both 2012 and 2013. Note that the dll is not included, and it is set to ignore version, so it will load the 2013 dll if that is what is present. 

I understand you are using a mix of 2012 build server, with TFS 2013, and with both VS 2012 and VS2013 installed on the build server.  
This should work, but obviously you are hitting some issue here.
1) Does this also happen when you build normally, that is without gated checkin ?
2) If you create a small test project, will that also fail the same way ?  And building normally (non-gated).  Or is it a particular solution that is failing ?  For the small test solution, keep all build settings at the default.
3) If you remove the test assemblies from the version control folder, and use the nuget approach instead - again with a small test solution, (follow the guidelines here http://blogs.msdn.com/b/visualstudioalm/archive/2013/06/11/part-3-unit-testing-with-traits-and-code-coverage-in-visual-studio-2012-using-the-tfs-build-and-the-new-nuget-adapter-approach.aspx , see section Providing 3rd party adapters through NuGet
4) You refer to "same problem" "VS2013, TFS 2012 AutomatedTest NUnit not working problems" - I assume you mean this stackoverflow post "http://stackoverflow.com/questions/28000370/vs2013-tfs-2012-automatedtest-nunit-not-working-problems" .  The solution there seems to be an upgrade of the TFS 2013.  This can indicate that having the controller on 2013 and the build server on 2012 can trigger this behaviour. 
It is not related to having both VS 2012 and VS2013 on the same machine, that scenario has been tested and found working. 
5) Changing the reference to 2012 should not have any effect, but you can build a version where you change this and try (or I can build one for you if you prefer). I would be very surprised if that solved anything, but I have been both surprised and wrong before :-)

**Comment by forestmarie** [comment]
Osiris, thanks for the quick response! 

Thank you for clearing up that the reference to VS2012 is intentional.  

I didn't mention in the original comment, but Visual Studio 2013 was something I installed on the build server this morning to see if it might help this issue.  Like you mentioned, it was one of those "I'll be surprised if this works" experiments, but it changed nothing. 

As for your comments: 

1. No - if I don't do this via a gated check-in, no tests are run so I'm fine there.

2. Yes - I can produce this on other projects using NUnit as well. 

3. I have removed the custom version controller assemblies from the controller and I get the same exact error message regarding not being able to locate ITestExecutorLauncher2.  

However, at least it proves that the build server is test adapter aware.  I wanted to double-check it by pulling the NUnit.TestAdapter out of packages.config and certainly it gave me warning that it could not load the following assemblies: nunit.util, nunit.interfaces and nunit.core.  When I put it back in one of my projects and checked-in, those warnings dropped.  So I was pleased here - I actually missed the news when TFS Build became test adapter aware, so thanks for that.    

I also double-checked that the adapter was not installed on the build server itself and it was not. 

4. Yes, that is the correct stackoverflow post I read - and I'm starting to get the feeling that upgrading my TFS build server is the only thing that will fix this.  I also posted this query on stackoverflow and the first comment I received was from one of the ALM Rangers asking why I'm using old build agents lol.  Short answer is I've not had an opportunity to upgrade it yet and really I had no reason to update them as we had been using MSTest for a long time with no issues but I'm trying to transition away from MSTest into NUnit as I really find value in [TestCase] :) 

5. I would love to try this, but I'm not sure how - I do not have the code for the adapter but it does seem like it would solve it - at least theoretically it should find ITestExecutorLauncher2.  If it's something you have handy I would prefer you build it and would be very appreciative of it.  Is this something you can put on NuGet or would I just need to drop it in the 3rd party dependencies solution and point the build controller back to use custom assemblies?

**Comment by forestmarie** [comment]
Osiris,

Just wanted to let you know that I installed a 2013 build controller and the 2013 build agents on my dev box scaling out my build process and used that controller in my build definition and it worked (same fix as the stackoverflow post). 

I tested both the version 11 and 12 process templates and they both worked as intended so I'll just spin up another VM tomorrow and install the 2013 agents there for our 2013 projects and I'll also see if all the 12 build definitions work flawlessly as well with the 2013 agents. 

Please don't worry about building that adapter. 

Thanks again for your help.

**Comment by OsirisTerje** [comment]
Great to hear the upgrade solved the issue :-)  

Just for curiosity:  You said "No - if I don't do this via a gated check-in, no tests are run so I'm fine there."  I might get you wrong here, but gated checkin is no requirement for building and running tests.   Running standard builds should work fine.  Did I understand you correct?

**Comment by forestmarie** [comment]
Yes. As long as no tests were being run I didn't have any issues.  With the 2013 build agents, I'm able to though.  Should have that new up today.

**Comment by OsirisTerje** [comment]
Great!  I think this can be closed then.  
If you get any more issues with this, just reopen it :-)
